[project]
name = "clut-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pillow>=11.3.0",
    "pyside6>=6.9.1",
    "scipy>=1.16.0",
    "screeninfo>=0.8.1",
]
